In [1]:
import numpy as np
import pandas as pd

In [2]:
recipe_df = pd.read_csv('/Users/malorycorteso/code/mariamorskovatykh/recipify/raw_data/RAW_recipes.csv')
recipe_df.head()

,name,id,minutes,contributor_id,submitted,tags,nutrition,n_steps,steps,description,ingredients,n_ingredients
0,arriba baked winter squash mexican style,137739,55,47892,2005-09-16,"['60-minutes-or-less', 'time-to-make', 'course...","[51.5, 0.0, 13.0, 0.0, 2.0, 0.0, 4.0]",11,"['make a choice and proceed with recipe', 'dep...",autumn is my favorite time of year to cook! th...,"['winter squash', 'mexican seasoning', 'mixed ...",7
1,a bit different breakfast pizza,31490,30,26278,2002-06-17,"['30-minutes-or-less', 'time-to-make', 'course...","[173.4, 18.0, 0.0, 17.0, 22.0, 35.0, 1.0]",9,"['preheat oven to 425 degrees f', 'press dough...",this recipe calls for the crust to be prebaked...,"['prepared pizza crust', 'sausage patty', 'egg...",6
2,all in the kitchen chili,112140,130,196586,2005-02-25,"['time-to-make', 'course', 'preparation', 'mai...","[269.8, 22.0, 32.0, 48.0, 39.0, 27.0, 5.0]",6,"['brown ground beef in large pot', 'add choppe...",this modified version of 'mom's' chili was a h...,"['ground beef', 'yellow onions', 'diced tomato...",13
3,alouette potatoes,59389,45,68585,2003-04-14,"['60-minutes-or-less', 'time-to-make', 'course...","[368.1, 17.0, 10.0, 2.0, 14.0, 8.0, 20.0]",11,['place potatoes in a large pot of lightly sal...,"this is a super easy, great tasting, make ahea...","['spreadable cheese with garlic and herbs', 'n...",11
4,amish tomato ketchup for canning,44061,190,41706,2002-10-25,"['weeknight', 'time-to-make', 'course', 'main-...","[352.9, 1.0, 337.0, 23.0, 3.0, 0.0, 28.0]",5,['mix all ingredients& boil for 2 1 / 2 hours ...,my dh's amish mother raised him on this recipe...,"['tomato juice', 'apple cider vinegar', 'sugar...",8

In [3]:
#removing white spaces
recipe_df.columns = recipe_df.columns.str.replace(' ', '')

In [4]:
#drop useless columns
recipe_df.drop(columns=['contributor_id', 'submitted', 'description'], inplace=True)

In [5]:
#cleaning data
recipe_df['ingredients'] = recipe_df['ingredients'].map(lambda x: x.lstrip('[').rstrip(']').replace("'", ""))
recipe_df['tags'] = recipe_df['tags'].map(lambda x: x.lstrip('[').rstrip(']').replace("'", ""))
recipe_df['nutrition'] = recipe_df['nutrition'].map(lambda x: x.lstrip('[').rstrip(']').replace("'", ""))
recipe_df['steps'] = recipe_df['steps'].map(lambda x: x.lstrip('[').rstrip(']').replace("'", ""))

In [6]:
#getting nutrition data in several columns(calories, sugar...)
recipe_df['calories'] = recipe_df['nutrition'].str.split(',').str[0]
recipe_df['total fat'] = recipe_df['nutrition'].str.split(',').str[1]
recipe_df['sugar'] = recipe_df['nutrition'].str.split(',').str[2]
recipe_df['sodium'] = recipe_df['nutrition'].str.split(',').str[3]
recipe_df['protein'] = recipe_df['nutrition'].str.split(',').str[4]
recipe_df['saturated fat'] = recipe_df['nutrition'].str.split(',').str[5]
recipe_df['carbohydrates'] = recipe_df['nutrition'].str.split(',').str[6]

In [7]:
recipe_df.drop(columns=['nutrition'], inplace=True)

In [8]:
recipe_df = recipe_df.rename(columns={'id': 'recipe_id'})

In [9]:
recipe_df.head()

,name,recipe_id,minutes,tags,n_steps,steps,ingredients,n_ingredients,calories,total fat,sugar,sodium,protein,saturated fat,carbohydrates
0,arriba baked winter squash mexican style,137739,55,"60-minutes-or-less, time-to-make, course, main...",11,"make a choice and proceed with recipe, dependi...","winter squash, mexican seasoning, mixed spice,...",7,51.5,0.0,13.0,0.0,2.0,0.0,4.0
1,a bit different breakfast pizza,31490,30,"30-minutes-or-less, time-to-make, course, main...",9,"preheat oven to 425 degrees f, press dough int...","prepared pizza crust, sausage patty, eggs, mil...",6,173.4,18.0,0.0,17.0,22.0,35.0,1.0
2,all in the kitchen chili,112140,130,"time-to-make, course, preparation, main-dish, ...",6,"brown ground beef in large pot, add chopped on...","ground beef, yellow onions, diced tomatoes, to...",13,269.8,22.0,32.0,48.0,39.0,27.0,5.0
3,alouette potatoes,59389,45,"60-minutes-or-less, time-to-make, course, main...",11,place potatoes in a large pot of lightly salte...,"spreadable cheese with garlic and herbs, new p...",11,368.1,17.0,10.0,2.0,14.0,8.0,20.0
4,amish tomato ketchup for canning,44061,190,"weeknight, time-to-make, course, main-ingredie...",5,"mix all ingredients& boil for 2 1 / 2 hours , ...","tomato juice, apple cider vinegar, sugar, salt...",8,352.9,1.0,337.0,23.0,3.0,0.0,28.0

In [11]:
review_df = pd.read_csv('/Users/malorycorteso/code/mariamorskovatykh/recipify/raw_data/RAW_interactions.csv')
len(review_df)

1132367

In [12]:
#checking duplicates
duplicate_count_review = len(review_df) - len(review_df.drop_duplicates()) 
#removing white spaces
review_df.columns = review_df.columns.str.replace(' ', '')

In [13]:
review_df.head()

,user_id,recipe_id,date,rating,review
0,38094,40893,2003-02-17,4,Great with a salad. Cooked on top of stove for...
1,1293707,40893,2011-12-21,5,"So simple, so delicious! Great for chilly fall..."
2,8937,44394,2002-12-01,4,This worked very well and is EASY. I used not...
3,126440,85009,2010-02-27,5,I made the Mexican topping and took it to bunk...
4,57222,85009,2011-10-01,5,"Made the cheddar bacon topping, adding a sprin..."

In [14]:
#removing useless columns for reviews
review_df.drop(columns=['user_id', 'date', 'review'], inplace=True)

In [15]:
review_df.head(5)

   recipe_id  rating
0      40893       4
1      40893       5
2      44394       4
3      85009       5
4      85009       5

In [16]:
avg_ratings = round(review_df.groupby('recipe_id')['rating'].mean(),2)

In [17]:
#adding the average rating in the recipe dataframe
recipe_df = pd.merge(recipe_df, avg_ratings, on = ['recipe_id'])
recipe_df.head()

,name,recipe_id,minutes,tags,n_steps,steps,ingredients,n_ingredients,calories,total fat,sugar,sodium,protein,saturated fat,carbohydrates,rating
0,arriba baked winter squash mexican style,137739,55,"60-minutes-or-less, time-to-make, course, main...",11,"make a choice and proceed with recipe, dependi...","winter squash, mexican seasoning, mixed spice,...",7,51.5,0.0,13.0,0.0,2.0,0.0,4.0,5.0
1,a bit different breakfast pizza,31490,30,"30-minutes-or-less, time-to-make, course, main...",9,"preheat oven to 425 degrees f, press dough int...","prepared pizza crust, sausage patty, eggs, mil...",6,173.4,18.0,0.0,17.0,22.0,35.0,1.0,3.5
2,all in the kitchen chili,112140,130,"time-to-make, course, preparation, main-dish, ...",6,"brown ground beef in large pot, add chopped on...","ground beef, yellow onions, diced tomatoes, to...",13,269.8,22.0,32.0,48.0,39.0,27.0,5.0,4.0
3,alouette potatoes,59389,45,"60-minutes-or-less, time-to-make, course, main...",11,place potatoes in a large pot of lightly salte...,"spreadable cheese with garlic and herbs, new p...",11,368.1,17.0,10.0,2.0,14.0,8.0,20.0,4.5
4,amish tomato ketchup for canning,44061,190,"weeknight, time-to-make, course, main-ingredie...",5,"mix all ingredients& boil for 2 1 / 2 hours , ...","tomato juice, apple cider vinegar, sugar, salt...",8,352.9,1.0,337.0,23.0,3.0,0.0,28.0,5.0

In [18]:
#Number of review by ratings
review_df.rating.value_counts(dropna=False)

5    816364
4    187360
0     60847
3     40855
2     14123
1     12818
Name: rating, dtype: int64

In [20]:
# list of recipes from the image dataset
list_recipe = pd.read_fwf('/Users/malorycorteso/code/mariamorskovatykh/recipify/raw_data/class_list.txt', header=None)
list_recipe.columns =['Name']
list_recipe['Name'] = list_recipe['Name'].str.replace('\d+', '')
list_recipe['Name'] = list_recipe['Name'].str.replace('_', ' ')
list_recipe.index.name = 'label'
list_recipe.head()

/var/folders/6c/6cswcqr149jdg3kvxmcdtz180000gn/T/ipykernel_2887/4150327554.py:4: FutureWarning: The default value of regex will change from True to False in a future version.
  list_recipe['Name'] = list_recipe['Name'].str.replace('\d+', '')

               Name
label
0           macaron
1           beignet
2           cruller
3       cockle food
4            samosa

In [21]:
list_recipe.shape

(251, 1)

In [22]:
#check how many recipes in the image dataset are in Food.com Recipes
list_recipes = []
for recipe in list_recipe['Name']:
    recipe = recipe.replace('food', '')
    recipe = recipe.replace('macaron', 'macarons')
    recipe = recipe.strip()
    if recipe_df['name'].str.contains(recipe).any():
        list_recipes.append(recipe)
list_recipes

['macarons',
 'beignet',
 'cruller',
 'samosa',
 'tiramisu',
 'tostada',
 'moussaka',
 'dumpling',
 'sashimi',
 'knish',
 'croquette',
 'couscous',
 'porridge',
 'stuffed cabbage',
 'seaweed salad',
 'chow mein',
 'rigatoni',
 'cannoli',
 'foie gras',
 'cupcake',
 'osso buco',
 'pad thai',
 'poutine',
 'ramen',
 'pulled pork sandwich',
 'bibimbap',
 'chicken kiev',
 'apple pie',
 'risotto',
 'fruitcake',
 'chop suey',
 'haggis',
 'scrambled eggs',
 'frittata',
 'scampi',
 'sushi',
 'orzo',
 'fritter',
 'nacho',
 'beef stroganoff',
 'beef wellington',
 'spring roll',
 'savarin',
 'crayfish',
 'souffle',
 'adobo',
 'streusel',
 'deviled egg',
 'escargot',
 'club sandwich',
 'carrot cake',
 'falafel',
 'farfalle',
 'terrine',
 'poached egg',
 'gnocchi',
 'bubble and squeak',
 'egg roll',
 'caprese salad',
 'sauerkraut',
 'creme brulee',
 'pavlova',
 'fondue',
 'scallop',
 'jambalaya',
 'tempura',
 'chocolate cake',
 'potpie',
 'spaghetti bolognese',
 'sukiyaki',
 'applesauce',
 'baklava',
 'salisbury steak',
 'linguine',
 'edamame',
 'coq au vin',
 'tamale',
 'kedgeree',
 'garlic bread',
 'beet salad',
 'steak tartare',
 'vermicelli',
 'pate',
 'pancake',
 'tetrazzini',
 'onion rings',
 'red velvet cake',
 'compote',
 'lobster',
 'chicken curry',
 'chicken wing',
 'caesar salad',
 'succotash',
 'hummus',
 'fish and chips',
 'lasagna',
 'lutefisk',
 'sloppy joe',
 'gingerbread',
 'crab cake',
 'sauerbraten',
 'peking duck',
 'guacamole',
 'ham sandwich',
 'crumpet',
 'taco',
 'strawberry shortcak',
 'clam chowder',
 'cottage pie',
 'croque madame',
 'french onion soup',
 'beef carpaccio',
 'torte',
 'poi',
 'crab',
 'bacon and eggs',
 'coffee cake',
 'custard',
 'syllabub',
 'pork chop',
 'fried rice',
 'boiled egg',
 'brisket',
 'reuben',
 'schnitzel',
 'ambrosia',
 'gyoza',
 'jerky',
 'ravioli',
 'fried calamari',
 'spaghetti carbonara',
 'miso soup',
 'frozen yogurt',
 'wonton',
 'panna cotta',
 'french toast',
 'enchilada',
 'ceviche',
 'fettuccine',
 'chili',
 'flan',
 'kabob',
 'sponge cake',
 'casserole',
 'paella',
 'blancmange',
 'bruschetta',
 'tortellini',
 'grilled salmon',
 'french fries',
 'shrimp and grits',
 'churro',
 'donut',
 'meat loaf',
 'meatball',
 'scrapple',
 'strudel',
 'coconut cake',
 'marble cake',
 'filet mignon',
 'hamburger',
 'fried egg',
 'tuna tartare',
 'penne',
 'eggs benedict',
 'bread pudding',
 'tenderloin',
 'chocolate mousse',
 'baked alaska',
 'hot dog',
 'confit',
 'ham and eggs',
 'biryani',
 'greek salad',
 'huevos rancheros',
 'tagliatelle',
 'stuffed peppers',
 'cannelloni',
 'pizza',
 'sausage roll',
 'chicken quesadilla',
 'hot and sour soup',
 'prime rib',
 'cheesecake',
 'ziti',
 'mussel',
 'manicotti',
 'ice cream',
 'waffle',
 'oyster',
 'omelette',
 'clam',
 'burrito',
 'roulade',
 'lobster bisque',
 'grilled cheese sand',
 'gyro',
 'pound cake',
 'pho',
 'lobster roll sandwi',
 'baby back rib',
 'tapenade',
 'pepper steak',
 'welsh rarebit',
 'pilaf',
 'dolmas',
 'coquilles saint jac',
 'veal cordon bleu',
 'shirred egg',
 'barbecued wing',
 'lobster thermidor',
 'steak au poivre',
 'huitre',
 'chiffon cake',
 'profiterole',
 'toad in the hole',
 'chicken marengo',
 'victoria sandwich',
 'tamale pie',
 'boston cream pie',
 'fish stick',
 'crumb cake',
 'chicken provencale',
 'vol au vent',
 'entrecote',
 'bacon lettuce tomat',
 'scotch egg',
 'pirogi',
 'peach melba',
 'upside down cake',
 'applesauce cake',
 'rugulah',
 'rock cake',
 'barbecued spareribs',
 'beef bourguignonne',
 'rissole',
 'mostaccioli',
 'apple turnover',
 'matzo ball',
 'chicken cordon bleu',
 'eccles cake',
 'moo goo gai pan',
 'buffalo wing',
 'stuffed tomato']

In [23]:
list_recipes2 = []
for recipe in list_recipe['Name']:
    recipe = recipe.strip('food').strip()
    if ~recipe_df['name'].str.contains(recipe).any():
        list_recipes2.append(recipe)
list_recipes2

['cockle',
 'beef tartare',
 'galantine',
 'takoyaki',
 'limpet',
 'carbonnade flamande']

In [24]:
len(list_recipes)

244

In [25]:
#list of recipe with our labels from images dataset
pattern = '|'.join(list_recipes)
new_recipe_df = recipe_df[recipe_df['name'].str.contains(pattern)==True]
new_recipe_df.shape

(51646, 16)

In [ ]:
new_recipe_df.to_csv (r'/Users/malorycorteso/code/mariamorskovatykh/recipify/recipe.csv', index=None)